# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'interfaceMock' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for interfaceMock
	pod 'ApiAI'

  target 'interfaceMockTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'interfaceMockUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
