# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ArMonster' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ArMonster
    #HTTP networking library
    pod 'Alamofire', '~> 4.5'
    #Auto Layout library
    pod 'SnapKit', '~> 4.0.0'
    #Promise
    pod 'PromiseKit', '~> 4.4'
    pod 'SVProgressHUD'
  target 'ArMonsterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ArMonsterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
